kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volume.claim.name }}
spec:
  storageClassName: "{{ .Values.volume.storageClassName }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi